apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neo4j-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neo4j-exporter.labels" . | nindent 4 }}
  {{- with (include "neo4j-exporter.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
data:
  config.yml: |
    {{- toYaml .Values.config | nindent 4 }}
