{{- if eq (include "neo4j-exporter.pdbEnabled" .) "true" -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "neo4j-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neo4j-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "neo4j-exporter.selectorLabels" . | nindent 6 }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
{{- end }}
